### ISSUE TITLE
Add commonjs build target

### ISSUE THREAD

**Issue by leroykorterink** [mediamonks/transition-component#133]
Many tools don't support esm yet which causes a lot of friction to make everything compatible. We can create a commonjs build and configure it so that the package can be used in more projects.

**Comment by ThaNarie** [comment]
I don't think we should go this route, but rather try to fix/patch the "source issues" of those tools; putting effort in driving things forward.

Because even if we add support back for CJS in our packages, there are tons of other packages out there, that we might get used in projects, that will still break those same tools again.
